# Generated by Django 4.0.4 on 2022-05-03 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Serie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('tipo', models.CharField(max_length=255)),
                ('plataforma', models.CharField(max_length=255)),
                ('fecha', models.DateField(default=2000)),
                ('episodio', models.IntegerField()),
                ('temporada', models.IntegerField()),
                ('terminada', models.BooleanField()),
                ('sinopsis', models.TextField()),
            ],
        ),
    ]
