# Generated by Django 4.0.4 on 2022-05-04 02:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paginas', '0003_alter_serie_codserie'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serie',
            name='codserie',
        ),
    ]
