# Generated by Django 4.0.4 on 2022-05-04 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paginas', '0004_remove_serie_codserie'),
    ]

    operations = [
        migrations.AddField(
            model_name='serie',
            name='codserie',
            field=models.CharField(default=None, max_length=25),
        ),
    ]
