# Generated by Django 4.0.4 on 2022-05-30 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paginas', '0006_alter_serie_codserie_alter_serie_terminada'),
    ]

    operations = [
        migrations.AddField(
            model_name='serie',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='series'),
        ),
        migrations.AlterField(
            model_name='serie',
            name='nombre',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='serie',
            name='plataforma',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='serie',
            name='tipo',
            field=models.CharField(max_length=30),
        ),
    ]
