# Generated by Django 4.0.4 on 2022-05-04 02:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='critico',
            old_name='Experencia',
            new_name='experiencia',
        ),
    ]
