# Generated by Django 4.0.4 on 2022-05-27 22:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_rename_experencia_critico_experiencia'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Usuario',
            new_name='Binger',
        ),
    ]
