# Generated by Django 4.0.4 on 2022-05-30 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='binger',
            name='alias',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='binger',
            name='apellido',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='binger',
            name='nombre',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='critico',
            name='alias',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='critico',
            name='apellido',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='critico',
            name='nombre',
            field=models.CharField(max_length=50),
        ),
        migrations.DeleteModel(
            name='Avatar',
        ),
    ]
